app: serverless-challenge
service: serverless-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions: 
  list-user:
    handler: src/list-user.handler
    events:
      - httpApi: 
          path: /users
          method: get
  create-user:
    handler: src/create-user.handler
    events:
      - httpApi:
          path: /users
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript