app: serverless-challenge
service: serverless-challenge
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions: 
  list-user:
    handler: src/list-user.handler
    events:
      - httpApi: 
          path: /users
          method: get
  create-user:
    handler: src/create-user.handler
    events:
      - httpApi:
          path: /users
          method: post
  update-user:
    handler: src/update-user.handler
    events:
      - httpApi:
          path: /user/{userId}
          method: put
          request:
            parameters:
              paths:
                userId: true
  show-user:
    handler: src/show-user.handler
    events:
      - httpApi:
          path: /user/{userId}
          method: get
          request:
            parameters:
              paths:
                userId: true
  delete-user:
    handler: src/delete-user.handler
    events:
      - httpApi:
          path: /user/{userId}
          method: delete
          request:
            parameters:
              paths:
                userId: true



plugins:
  - serverless-offline
  - serverless-plugin-typescript